### ISSUE TITLE
Question about Share Affinity

### ISSUE THREAD

**Issue by uaiaaaa** [JiaweiShiCV/Amend-Representation-Module#1]
Hi, sunmusik. Nice work.
But I don't quite understand why we should add the mean of one batch's features to each feature of the batch and when it comes to test phase, we still need to add the mean of the batch's features in order to produce a high classification accuracy. If I  add the mean of one batch's features to each feature of the batch only in the train phase, the accuracy drops significantly.
Can you explain the principle behind SA module about why it can bring an increase in classification accuracy mostly in Netural Expression class? Thanks a lot.

**Comment by sunmusik** [comment]
Well, I consider that the complexity of ResNet-18 is not enough to fit the face space. When learning to recognize facial expressions, neurons are just sensitive to specific features hat are most conducive to the recognition rate, and this will lead to one-sided feature learning. I have tried to deepen the network but the network tends to overfit due to the limitation of the dataset. Facial expressions are all variations of human faces, so we apply this method to refine the representations of each expression. Perhaps this problem does not exist on larger datasets and deeper networks.

**Comment by uaiaaaa** [comment]
Really appreciate your help. One more thing, after the train phase, I think the model should already be sensitive to the global representations of faces instead of specific features. But if l don't add the mean features in test phase, the network can't get very high recognition rate. Do you know why? Thanks a lot.

**Comment by JiaweiShiCV** [comment]
> 非常感谢您的帮助。还有一件事，在训练阶段之后，我认为模型应该已经对人脸的全局表示敏感，而不是特定特征。但是，如果不在测试阶段添加均值特征，则网络将无法获得很高的识别率。你知道为什么吗？非常感谢。

I think due to the limitation of network complexity, the learning ability of ResNet18 has reached saturation. The network has this ability just because of mandatory intervention.

**Comment by JiaweiShiCV** [comment]
> Really appreciate your help. One more thing, after the train phase, I think the model should already be sensitive to the global representations of faces instead of specific features. But if l don't add the mean features in test phase, the network can't get very high recognition rate. Do you know why? Thanks a lot.

I think due to the limitation of network complexity, the learning ability of Resnt18 has reached saturation. The network has this ability only because of mandatory intervention.

**Comment by uaiaaaa** [comment]
Thanks a lot for your kind explanation.
