### ISSUE TITLE
About the acc results on SFEW 

### ISSUE THREAD

**Issue by myt889** [JiaweiShiCV/Amend-Representation-Module#15]
Hi,JiaweiShiCV
     You reported the Acc of 51.56% on SFEW dataset with only ResNet18 backbone pretrained on ImageNet, how can you do that? I did the same data processing as you did,but just obtained 45%. I was confused, looking forward to your reply,thank you very much.

**Comment by JiaweiShiCV** [comment]
Thank you for your attention. Obviously, the operation used to train raf-db cannot be directly applied to SFEW, because the distribution of the two is quite different. We cannot train the original ResNet-18 with such a small amount of data. A modification was applied to the backbone of SFEW, resulting in a decrease in the amount of parameters. Corresponding to different data sets, the configuration of the ARM module has also been adjusted.

**Comment by myt889** [comment]
> Thank you for your attention. Obviously, the operation used to train raf-db cannot be directly applied to SFEW, because the distribution of the two is quite different. We cannot train the original ResNet-18 with such a small amount of data. A modification was applied to the backbone of SFEW, resulting in a decrease in the amount of parameters. Corresponding to different data sets, the configuration of the ARM module has also been adjusted.

Ok,I get it. Thank you so much.
